name: SBlock

main: co.sblock.Sblock.Sblock
version: 2.0.0-DEV
author: Sblock Co.
authors: [Dublek, Jikoo, FireNG]
description: Sblock's sexy mainframe
commands:
 sc:
  usage: /sc <action> <additional arguments>
  description: "[Sburb] SburbChat's main command"
 sban:
  usage: /<command> <target> <reason>
  description: "[Sburb] Ban a player and their IP address."
 profile:
  usage: /<command> <username>
  description: "[Sburb] Show's a player's Sburb profile"
 setplayer:
  usage: /<command> <playername> <class|aspect|land|dream> <value>
  description: "[Sburb] Change's a player's information."
 newplayer:
  usage: /<command> <playername> <class> <aspect> <medium planet> <dream planet>
  description: "[Sburb] Sets up a new player with the given options."
  