name: Easterlyn

main: com.easterlyn.Easterlyn
version: ${timestamp}
author: Jikoo
authors: [Dublek, FireNG, tmathmeyer]
description: https://www.youtube.com/watch?v=QHnJ9NmK3Pc
depend: [GriefPrevention, ProtocolLib, WorldEdit, WorldGuard]
softdepend: [CreeperHeal, dynmap, Regionerator, LuckPerms]
api-version: 1.13

permissions:
 easterlyn.guildleader:
  description: 'Default false - not all horrorterrors are guild leaders.'
  default: false
