name: Easterlyn

main: com.easterlyn.Easterlyn
version: ${timestamp}
author: Jikoo
authors: [Dublek, FireNG, tmathmeyer]
description: https://www.youtube.com/watch?v=QHnJ9NmK3Pc
depend: [GriefPrevention, ProtocolLib, WorldEdit, WorldGuard]
softdepend: [CreeperHeal, dynmap, Regionerator, zPermissions]

permissions:
 easterlyn.group.ask.adam.before.touching:
  description: 'If something requires this permission, you probably shouldn''t be touching it.'
  default: false
 easterlyn.guildleader:
  description: 'Default false - not all horrorterrors are guild leaders.'
  default: false
