name: Easterlyn

main: com.easterlyn.Easterlyn
version: ${timestamp}
author: Jikoo
authors: [Dublek, FireNG, tmathmeyer]
description: Sblock's sexy mainframe
depend: [GriefPrevention, ProtocolLib, WorldEdit, WorldGuard]
softdepend: [CreeperHeal, dynmap, Regionerator, zPermissions]

permissions:
 sblock.ask.adam.before.touching:
  description: 'If something requires this permission, you probably shouldn''t be touching it.'
  default: false
 sblock.guildleader:
  description: 'Default false - not all horrorterrors are guild leaders.'
  default: false
 sblock.god:
  description: 'Stuff for Sblock "gods"'
  default: false
