name: Sblock

main: co.sblock.Sblock
version: {BUILD}
author: Sblock Co.
authors: [Jikoo, Dublek, FireNG, tmathmeyer]
description: Sblock's sexy mainframe
depend: [ProtocolLib]
softdepend: [CreeperHeal, dynmap, HolographicDisplays, WorldEdit]

permissions:
 sblock.ask.adam.before.touching:
  description: 'If something requires this permission, you probably shouldn''t be touching it.'
  default: false
 sblock.guildleader:
  description: 'Default false - not all horrorterrors are guild leaders.'
  default: false
 sblockchat.greentext:
  description: '>mfw tfw'
  default: true
 sblockchat.color:
  description: 'Automatically colors message with name color.'
  default: false
