name: Sblock

main: co.sblock.Sblock.Sblock
version: 2.0.0-DEV
author: Sblock Co.
authors: [Dublek, Jikoo, FireNG]
description: Sblock's sexy mainframe
depend: [ProtocolLib, BKCommonLib]

commands:
 le:
  usage: /le <text>
  description: Well, this is a fascinating tale-- OH GOD THERE'S NO TIME, HE'S ALREADY HERE.
 lel:
  usage: /lel <text>
  description: /le, now with 250% more brainhurtiness
 whois:
  usage: /whois <target>
  description: Garner information
 scban:
  usage: /scban <target>
  description: NO ONE ESCAPES THE RED MILES.
 o:
  usage: /o <text>
  description: '> Be Doc Scratch.'
 quit:
  usage: /quit <optional text>
  description: '> Player: Exit'
 sc:
  usage: /sc ? for help
  description: "SburbChat's main command"
 sban:
  usage: /<command> <target> <reason>
  description: "Ban a player and their IP address."
  permission: group.horrorterror
 unsban:
  usage: /<command> <target>
  description: "Undo the effects of sban."
  permission: group.horrorterror
 profile:
  usage: /<command> <username>
  description: "Shows a player's Sburb profile"
 setplayer:
  usage: /<command> <playername> <class|aspect|land|dream> <value>
  description: "Changes a player's information."
  permission: group.horrorterror
 settower:
  usage: /settower <number>
  description: "Set tower teleport location to current for tower <number>"
  permission: group.horrorterror
 dragon:
  usage: /dragon
  description: death by awesome
  permission: group.horrorterror
 meteormod:
  usage: /meteormod <p:player> <r:radius> <e:explode> <c:countdown> <m:material>
  description: Summon a meteor with ALL the parameters
 meteor:
  usage: /meteor
  description: Drop a meteor on the crosshairs
 se:
  description: Root of all SburbEffects commands
  usage: /se <getlore/setlore/clearlore/applyeffects/verbose> <lore>
