name: Sblock

main: co.sblock.Sblock.Sblock
version: 2.0.0-DEV
author: Sblock Co.
authors: [Dublek, Jikoo, FireNG]
description: Sblock's sexy mainframe
commands:
 le:
  usage: /le <text>
  description: Well, this is a fascinating tale-- OH GOD THERE'S NO TIME, HE'S ALREADY HERE.
 lel:
  usage: /lel <text>
  description: /le, now with 250% more brainhurtiness
 whois:
  usage: /whois <target>
  description: Garner information
 scban:
  usage: /scban <target>
  description: NO ONE ESCAPES THE RED MILES.
 o:
  usage: /o <text>
  description: '> Be Doc Scratch.'
 sc:
  usage: /sc ? for help
  description: "[Sburb] SburbChat's main command"
 sban:
  usage: /<command> <target> <reason>
  description: "[Sburb] Ban a player and their IP address."
 unsban:
  usage: /<command> <target>
  description: "[Sburb] Undo the effects of sban."
 profile:
  usage: /<command> <username>
  description: "[Sburb] Show's a player's Sburb profile"
 setplayer:
  usage: /<command> <playername> <class|aspect|land|dream> <value>
  description: "[Sburb] Change's a player's information."
 newplayer:
  usage: /<command> <playername> <class> <aspect> <medium planet> <dream planet>
  description: "[Sburb] Sets up a new player with the given options."
  