name: Sblock

main: co.sblock.Sblock
version: 2.0.0-DEV
author: Sblock Co.
authors: [Jikoo, Dublek, FireNG, tmathmeyer]
description: Sblock's sexy mainframe
depend: [ProtocolLib]
softdepend: [CreeperHeal]

permissions:
 sblock.blaze:
  description: Permission for Blazing Saddles
  default: op
 sblock.ask.adam.before.touching:
  description: If something requires this permission, you probably shouldn't be touching it.
  default: false
 sblock.guildleader:
  description: Default false - not all horrorterrors are guild leaders.
  default: false
 sblockchat.color:
  description: Autmatically colors message with name color.
  default: false
 sblockchat.black:
  default: false
 sblockchat.dark_blue:
  default: false
 sblockchat.dark_green:
  default: false
 sblockchat.dark_aqua:
  default: false
 sblockchat.dark_red:
  default: false
 sblockchat.dark_purple:
  default: false
 sblockchat.gold:
  default: false
 sblockchat.gray:
  default: false
 sblockchat.dark_gray:
  default: false
 sblockchat.blue:
  default: false
 sblockchat.green:
  default: false
 sblockchat.aqua:
  default: false
 sblockchat.red:
  default: false
 sblockchat.light_purple:
  default: false
 sblockchat.yellow:
  default: false
 sblockchat.white:
  default: false
 sblockchat.magic:
  default: false
 sblockchat.bold:
  default: false
 sblockchat.strikethrough:
  default: false
 sblockchat.underline:
  default: false
 sblockchat.italic:
  default: false
 sblockchat.reset:
  default: false
